sudo: false
language: go
go:
  - 1.9

env:
  global:
    secure: swil3Y+gIZkN/Ch6NF13dM1QPF+rABiW5kTSP149arwwu1tcDGIv/64zifGzrOxkrez9ZUQzJs5fqsBtRX5p4Q8hC7s8D+3On5TqLovPUr4Pu5Fjy4VJdGz6NaD1Zp1hcwBPJo30efI16utACfjDSuvGhc2s3W98LmZJajaNqVbDFYOkCgZQgIToWeMQ25ZcObvsM+RrJUsZMndSaCZ0N4JTA3fb4uygOmd60qo/kcoiYbp7daP0cshq9IggcQPlPgVraodmY4MLy5bCRHtN6xzqa0DfzvGHqPp815pIYCYi2AxfdkrnUz1ZZxGIv7lrC4MHe+kC7YSe1YhJYfxEFInXhbOd5bcdQeJ0By1V0woku5wzXU7MrE4ZqzABYUhbEFdyWFrBqkvMWkLE70uFhpRxQgE8x9C0qbjY7/yNK0RRPXyiGn98kk6eio+H1fPdxUI/PlrmblUiObvjnWZo+rSWajSlzdYzFvY+OOrP3H7dSQTbotsqqqQYyIILxOX+zbQR+SNlRURqhra7xOreYSSaCyZBzCi0O3B4iz2AdwRdb6OVz7YRIJZuOr02Ht+H0csnzMs3IWHxjLxB6SmpQvZ1cMUy04vgQWsghcTip1jVsU5oTYLtW0V501p0DjcLdzKo6lj+fddjMLeV0Ok6S1v717Cu03DaMYzbp2VnXjI=
    - GO111MODULE=on

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover;
    fi

before_script:
  - go vet ./...
  - gofmt -s -l .

script:
  - go test -v -covermode=count -coverprofile=coverage.out
  - "$HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken
    $COVERALLS_TOKEN"
