sudo: false
language: go
go:
  - 1.9

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
before_script:
  - go vet ./...
  - gofmt -s -l .
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
